chrome.extension.sendMessage({}, function(response) {
	var readyStateCheckInterval = setInterval(function() {
	if (document.readyState === "complete") {
		clearInterval(readyStateCheckInterval);
		// Placeholder player array for now, will figure out what to put later
		var playerNames = ["5", "Acorn", "Adrian", "Altec", "Aluka", "Ambition", "Amel", "Aphromoo", "Apollo", "Arrow", "Azingy", "Bang", "Bdd", "Bei", "Benny", "Big", "BillyBoss", "Biofrost", "Bjergsen", "Blanc", "Blank", "Borisal", "Bubbling", "Bunny FuFuu", "Caveman", "Chaser", "Chei", "Chimin", "ClearLove", "Coco", "Conan", "Condi", "Cool", "CoreJJ", "Cpt Jack", "Cris", "Crisis", "Crown", "Crumbzz", "Crush", "CuVee", "DanDy", "Dardoch", "Darshan", "Deft", "Doinb", "Doublelift", "Duke", "EShen", "Easyhoon", "Edge", "Eimy", "Ella", "Expession", "Faker", "Feng", "FeniX", "FishBall", "Flame", "Flandre", "Flawless", "Fly", "Freeze", "Froggen", "Frozen", "Fury", "GBM", "Gate", "Ghost", "GimGoon", "GorillA", "Gosu", "GuGer", "Hachani", "Hai", "Hard", "Hauntzer", "Helios", "Hi Im Gosu", "Hipo", "HotshotGG", "HuHi", "Huni", "Icon", "Impact", "Impactful", "Inori", "Jensen", "Jia", "JieZou", "Jinoo", "JoJo", "JueJue", "Jynthe", "KRYST4L", "Keith", "KiWiKiD", "Kid", "Kirei", "Kitties", "KonKwon", "Koro1", "Kramer", "Kuro", "Kuzan", "LetMe", "Ley", "Lindarang", "Loong", "Looper", "Lourlo", "Lovecd", "Luo", "MaRin", "MadLife", "March", "Martin", "Mash", "Mata", "Matt", "Memory", "Meteos", "Mickey", "Mitty", "Mlxg", "Mo", "Moon", "MorZB", "Mortred", "Move", "Mystic", "NaMei", "Ninja", "Nuclear", "Nyjacky", "Patoy", "PawN", "Peanut", "PentaQ", "Piglet", "Pilot", "Pirean", "Pobelter", "PraY", "Procxin", "Pure", "Pyl", "Quan", "Rabbit97", "Rain", "Raphael", "Reignover", "Republic", "Roach", "Romant1c", "RooKie", "Ruler", "Ruo", "Rush", "SaSin", "Sakuya", "Sangyoon", "Sask", "Savoki", "Score", "Secret", "Seonghwan", "Seraph", "Shiphtur", "Shrimp", "Shy", "Sky", "SmLz", "Smeb", "SmittyJ", "Smoothie", "Sneaky", "SnowFlower", "SoHwan", "SoaR", "Soul", "Ss17", "Ssol", "Ssumday", "Star", "Stitch", "Stixxay", "Swift", "Time", "Tom", "U", "Untara", "Uzi", "V", "Valkrin", "Vasilii", "We1less", "WildTurtle", "Winged", "Wolf", "Wraith", "Wuxx", "X1u", "XQ", "XY", "Xiaohu", "Xiyang", "Xiye", "Xmithie", "Yazuki", "YellOwStaR", "Yolo", "Youngbin", "Yu", "Zero", "Zzitai", "Zzr", "Zzus", "bengi", "fabbbyyy", "ikssu", "imp", "inSec", "kfo", "lira", "maplestreet8", "meiko"];

		// Looks at page and replace every occurance of the known playerName with "teemo"
	}
	}, 10);
});